# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"5\n\x04Root\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x1d\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\r.NestedObject\"\x9f\x01\n\x0cNestedObject\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x04\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\t\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x03\x12\x1e\n\x06\x66ield9\x18\t \x01(\x0b\x32\x0e.NestedDetails\x12\x1f\n\x07\x66ield13\x18\r \x01(\x0b\x32\x0e.NestedOptions\"`\n\rNestedDetails\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\t\x12\x0f\n\x07\x66ield10\x18\n \x01(\x05\"?\n\rNestedOptions\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOT']._serialized_start=14
  _globals['_ROOT']._serialized_end=67
  _globals['_NESTEDOBJECT']._serialized_start=70
  _globals['_NESTEDOBJECT']._serialized_end=229
  _globals['_NESTEDDETAILS']._serialized_start=231
  _globals['_NESTEDDETAILS']._serialized_end=327
  _globals['_NESTEDOPTIONS']._serialized_start=329
  _globals['_NESTEDOPTIONS']._serialized_end=392
# @@protoc_insertion_point(module_scope)
